[2022-12-31T21:18:22.720+0700] {processor.py:153} INFO - Started process (PID=23708) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:22.721+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:18:22.721+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:22.721+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:22.729+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:22.728+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:18:22.729+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:22.753+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-12-31T21:18:47.000+0700] {processor.py:153} INFO - Started process (PID=23951) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:47.000+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:18:47.001+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:47.001+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:47.009+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:47.007+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:18:47.009+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:18:47.039+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.042 seconds
[2022-12-31T21:19:36.767+0700] {processor.py:153} INFO - Started process (PID=24147) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:36.771+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:19:36.773+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:36.773+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:36.784+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:36.782+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:19:36.784+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:36.814+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-12-31T21:19:56.513+0700] {processor.py:153} INFO - Started process (PID=24227) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:56.515+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:19:56.515+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:56.515+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:56.524+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:56.524+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:19:56.525+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:19:56.551+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.041 seconds
[2022-12-31T21:20:19.434+0700] {processor.py:153} INFO - Started process (PID=24428) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:19.438+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:20:19.439+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:19.439+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:19.451+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:19.450+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:20:19.452+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:19.479+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.050 seconds
[2022-12-31T21:20:42.476+0700] {processor.py:153} INFO - Started process (PID=24469) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:42.478+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:20:42.479+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:42.479+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:42.497+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:42.495+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:20:42.497+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:20:42.527+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.056 seconds
[2022-12-31T21:22:00.161+0700] {processor.py:153} INFO - Started process (PID=24889) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:22:00.162+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:22:00.163+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:22:00.162+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:22:00.173+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:22:00.171+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:22:00.173+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:22:00.203+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-12-31T21:23:00.057+0700] {processor.py:153} INFO - Started process (PID=25363) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:00.062+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:23:00.065+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:00.064+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:00.105+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:00.100+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:23:00.106+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:00.161+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.121 seconds
[2022-12-31T21:23:20.415+0700] {processor.py:153} INFO - Started process (PID=25418) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:20.417+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:23:20.419+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:20.419+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:20.436+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:20.435+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:23:20.437+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:20.464+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.056 seconds
[2022-12-31T21:23:43.585+0700] {processor.py:153} INFO - Started process (PID=25451) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:43.590+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:23:43.591+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:43.591+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:43.612+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:43.610+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:23:43.613+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:23:43.638+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.060 seconds
[2022-12-31T21:24:16.720+0700] {processor.py:153} INFO - Started process (PID=25595) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:16.724+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:24:16.726+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:16.726+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:16.743+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:16.741+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:24:16.744+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:16.770+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.058 seconds
[2022-12-31T21:24:45.594+0700] {processor.py:153} INFO - Started process (PID=25689) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:45.596+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:24:45.597+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:45.597+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:45.608+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:45.607+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:24:45.608+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:24:45.639+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.048 seconds
[2022-12-31T21:25:05.603+0700] {processor.py:153} INFO - Started process (PID=25736) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:05.608+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:25:05.609+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:05.609+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:05.627+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:05.625+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:25:05.627+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:05.656+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.059 seconds
[2022-12-31T21:25:24.469+0700] {processor.py:153} INFO - Started process (PID=25837) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:24.470+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:25:24.471+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:24.471+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:24.490+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:24.488+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:25:24.490+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:24.530+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.066 seconds
[2022-12-31T21:25:44.905+0700] {processor.py:153} INFO - Started process (PID=25874) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:44.909+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:25:44.913+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:44.912+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:44.948+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:44.943+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:25:44.950+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:25:45.007+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.116 seconds
[2022-12-31T21:26:07.857+0700] {processor.py:153} INFO - Started process (PID=25915) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:07.860+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:26:07.865+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:07.864+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:07.887+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:07.885+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:26:07.887+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:07.923+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.083 seconds
[2022-12-31T21:26:34.412+0700] {processor.py:153} INFO - Started process (PID=25970) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:34.418+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:26:34.420+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:34.420+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:34.468+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:34.462+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:26:34.469+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:26:34.631+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.230 seconds
[2022-12-31T21:27:00.353+0700] {processor.py:153} INFO - Started process (PID=26008) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:00.353+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:27:00.354+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:00.354+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:00.365+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:00.363+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:27:00.365+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:00.397+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.048 seconds
[2022-12-31T21:27:35.953+0700] {processor.py:153} INFO - Started process (PID=26078) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:35.958+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:27:35.960+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:35.960+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:35.994+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:35.991+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:27:35.996+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:27:36.052+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.112 seconds
[2022-12-31T21:28:05.327+0700] {processor.py:153} INFO - Started process (PID=26129) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:05.329+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:28:05.332+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:05.331+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:05.361+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:05.359+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:28:05.362+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:05.395+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.077 seconds
[2022-12-31T21:28:26.572+0700] {processor.py:153} INFO - Started process (PID=26165) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:26.575+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:28:26.577+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:26.577+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:26.599+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:26.597+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:28:26.600+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:26.632+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.070 seconds
[2022-12-31T21:28:46.390+0700] {processor.py:153} INFO - Started process (PID=26219) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:46.393+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:28:46.395+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:46.395+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:46.434+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:46.429+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:28:46.435+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:28:46.477+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.098 seconds
[2022-12-31T21:29:06.137+0700] {processor.py:153} INFO - Started process (PID=26261) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:06.140+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:29:06.142+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:06.142+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:06.159+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:06.157+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:29:06.160+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:06.205+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.073 seconds
[2022-12-31T21:29:28.584+0700] {processor.py:153} INFO - Started process (PID=26303) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:28.586+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:29:28.587+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:28.587+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:28.605+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:28.602+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:29:28.606+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:28.641+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.061 seconds
[2022-12-31T21:29:50.207+0700] {processor.py:153} INFO - Started process (PID=26376) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:50.213+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:29:50.215+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:50.215+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:50.258+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:50.253+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:29:50.260+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:29:50.311+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.116 seconds
[2022-12-31T21:30:25.569+0700] {processor.py:153} INFO - Started process (PID=26450) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:25.574+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:30:25.578+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:25.577+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:25.600+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:25.598+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:30:25.601+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:25.633+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.074 seconds
[2022-12-31T21:30:59.357+0700] {processor.py:153} INFO - Started process (PID=26516) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:59.365+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:30:59.369+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:59.368+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:59.411+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:59.406+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:30:59.413+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:30:59.456+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.111 seconds
[2022-12-31T21:31:20.691+0700] {processor.py:153} INFO - Started process (PID=26553) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:20.692+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:31:20.694+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:20.693+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:20.725+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:20.722+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:31:20.726+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:20.778+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.095 seconds
[2022-12-31T21:31:44.228+0700] {processor.py:153} INFO - Started process (PID=26590) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:44.234+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:31:44.236+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:44.235+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:44.279+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:44.274+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:31:44.281+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:31:44.314+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.098 seconds
[2022-12-31T21:32:05.679+0700] {processor.py:153} INFO - Started process (PID=26627) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:05.682+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:32:05.685+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:05.684+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:05.719+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:05.716+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:32:05.719+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:05.757+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.090 seconds
[2022-12-31T21:32:26.557+0700] {processor.py:153} INFO - Started process (PID=26676) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:26.563+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:32:26.565+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:26.565+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:26.593+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:26.591+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:32:26.593+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:26.631+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.085 seconds
[2022-12-31T21:32:49.471+0700] {processor.py:153} INFO - Started process (PID=26718) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:49.474+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:32:49.478+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:49.477+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:49.514+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:49.509+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:32:49.516+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:32:49.557+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.097 seconds
[2022-12-31T21:33:26.114+0700] {processor.py:153} INFO - Started process (PID=26793) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:26.120+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:33:26.123+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:33:26.122+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:26.151+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:33:26.149+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:33:26.151+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:26.183+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.081 seconds
[2022-12-31T21:33:54.475+0700] {processor.py:153} INFO - Started process (PID=26844) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:54.475+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:33:54.476+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:33:54.476+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:54.483+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:33:54.483+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:33:54.484+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:33:54.508+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-12-31T21:34:11.787+0700] {processor.py:153} INFO - Started process (PID=27334) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:11.792+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:34:11.794+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:11.794+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:11.810+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:11.808+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:34:11.811+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:11.836+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.052 seconds
[2022-12-31T21:34:19.927+0700] {processor.py:153} INFO - Started process (PID=27471) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:19.928+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:34:19.929+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:19.928+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:19.936+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:19.935+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:34:19.936+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:34:19.962+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.037 seconds
[2022-12-31T21:35:07.577+0700] {processor.py:153} INFO - Started process (PID=27707) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:07.582+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:35:07.584+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:07.584+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:07.603+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:07.601+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:35:07.604+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:07.631+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.061 seconds
[2022-12-31T21:35:25.669+0700] {processor.py:153} INFO - Started process (PID=27868) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:25.669+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:35:25.670+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:25.670+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:25.677+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:25.676+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:35:25.678+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:25.703+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-12-31T21:35:47.602+0700] {processor.py:153} INFO - Started process (PID=27918) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:47.606+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:35:47.607+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:47.607+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:47.619+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:47.618+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:35:47.619+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:35:47.648+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.048 seconds
[2022-12-31T21:37:49.841+0700] {processor.py:153} INFO - Started process (PID=28651) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:37:49.842+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:37:49.842+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:37:49.842+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:37:49.850+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:37:49.849+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:37:49.851+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:37:49.876+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.037 seconds
[2022-12-31T21:38:43.885+0700] {processor.py:153} INFO - Started process (PID=28992) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:38:43.887+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:38:43.889+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:43.889+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:38:43.910+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:43.909+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:38:43.911+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:38:43.940+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.057 seconds
[2022-12-31T21:39:05.236+0700] {processor.py:153} INFO - Started process (PID=29083) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:05.239+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:39:05.241+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:05.241+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:05.265+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:05.263+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:39:05.266+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:05.299+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.071 seconds
[2022-12-31T21:39:29.364+0700] {processor.py:153} INFO - Started process (PID=29132) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:29.368+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:39:29.369+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:29.369+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:29.387+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:29.385+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:39:29.388+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:29.426+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.068 seconds
[2022-12-31T21:39:54.013+0700] {processor.py:153} INFO - Started process (PID=29238) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:54.014+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:39:54.015+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:54.015+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:54.027+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:54.026+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:39:54.027+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:39:54.056+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.047 seconds
[2022-12-31T21:40:18.147+0700] {processor.py:153} INFO - Started process (PID=29281) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:18.152+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:40:18.155+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:18.154+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:18.174+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:18.172+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:40:18.175+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:18.202+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.063 seconds
[2022-12-31T21:40:41.990+0700] {processor.py:153} INFO - Started process (PID=29470) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:41.991+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:40:41.991+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:41.991+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:41.999+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:41.998+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:40:42.000+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:40:42.024+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.036 seconds
[2022-12-31T21:41:04.628+0700] {processor.py:153} INFO - Started process (PID=29508) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:04.632+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:41:04.633+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:04.632+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:04.640+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:04.639+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:41:04.641+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:04.666+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.040 seconds
[2022-12-31T21:41:25.607+0700] {processor.py:153} INFO - Started process (PID=29538) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:25.608+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:41:25.609+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:25.609+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:25.620+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:25.619+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:41:25.621+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:25.650+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-12-31T21:41:50.436+0700] {processor.py:153} INFO - Started process (PID=29704) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:50.438+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:41:50.438+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:50.438+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:50.445+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:50.444+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:41:50.446+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:41:50.471+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.038 seconds
[2022-12-31T21:42:40.584+0700] {processor.py:153} INFO - Started process (PID=29864) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:40.587+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:42:40.589+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:40.589+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:40.597+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:40.596+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:42:40.597+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:40.624+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.042 seconds
[2022-12-31T21:42:59.021+0700] {processor.py:153} INFO - Started process (PID=29901) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:59.022+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:42:59.023+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:59.023+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:59.030+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:59.029+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:42:59.031+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:42:59.057+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-12-31T21:43:18.654+0700] {processor.py:153} INFO - Started process (PID=30001) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:18.656+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:43:18.657+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:43:18.657+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:18.664+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:43:18.664+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:43:18.665+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:18.690+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.039 seconds
[2022-12-31T21:43:38.868+0700] {processor.py:153} INFO - Started process (PID=30199) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:38.868+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T21:43:38.869+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:43:38.869+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:38.879+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:43:38.878+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T21:43:38.879+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T21:43:38.913+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.048 seconds
[2022-12-31T22:20:35.109+0700] {processor.py:153} INFO - Started process (PID=45890) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:20:35.115+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:20:35.116+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:20:35.116+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:20:35.125+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:20:35.124+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:20:35.125+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:20:35.151+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.045 seconds
[2022-12-31T22:21:07.277+0700] {processor.py:153} INFO - Started process (PID=46574) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:07.284+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:21:07.284+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:21:07.284+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:07.292+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:21:07.291+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:21:07.292+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:07.321+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.046 seconds
[2022-12-31T22:21:30.029+0700] {processor.py:153} INFO - Started process (PID=46774) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:30.030+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:21:30.031+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:21:30.030+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:30.039+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:21:30.038+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:21:30.039+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:21:30.071+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.045 seconds
[2022-12-31T22:22:10.898+0700] {processor.py:153} INFO - Started process (PID=47170) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:10.901+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:22:10.901+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:10.901+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:10.909+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:10.908+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:22:10.910+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:10.941+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.047 seconds
[2022-12-31T22:22:49.585+0700] {processor.py:153} INFO - Started process (PID=47435) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:49.588+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:22:49.588+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:49.588+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:49.599+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:49.597+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:22:49.600+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:22:49.631+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.049 seconds
[2022-12-31T22:23:36.933+0700] {processor.py:153} INFO - Started process (PID=47768) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:36.939+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:23:36.944+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:36.944+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:36.965+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:36.963+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:23:36.966+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:36.999+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.072 seconds
[2022-12-31T22:23:55.796+0700] {processor.py:153} INFO - Started process (PID=47965) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:55.798+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:23:55.800+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:55.800+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:55.819+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:55.817+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:23:55.819+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:23:55.852+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.065 seconds
[2022-12-31T22:24:19.532+0700] {processor.py:153} INFO - Started process (PID=48175) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:19.535+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:24:19.536+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:19.536+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:19.549+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:19.547+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:24:19.549+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:19.588+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.061 seconds
[2022-12-31T22:24:46.103+0700] {processor.py:153} INFO - Started process (PID=48498) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:46.104+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:24:46.105+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:46.105+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:46.118+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:46.117+0700] {dagbag.py:343} ERROR - Failed to import: /home/dmk/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dmk/airflow/dags/twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/home/dmk/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.apache.hive'
[2022-12-31T22:24:46.119+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:24:46.158+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.063 seconds
[2022-12-31T22:25:01.381+0700] {processor.py:153} INFO - Started process (PID=48748) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:01.384+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:25:01.387+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.386+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:01.720+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:25:01.721+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:25:01.739+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:25:01.754+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:01.889+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.889+0700] {manager.py:504} INFO - Created Permission View: can read on DAG:twitter_dag
[2022-12-31T22:25:01.912+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.911+0700] {manager.py:504} INFO - Created Permission View: can edit on DAG:twitter_dag
[2022-12-31T22:25:01.933+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.933+0700] {manager.py:504} INFO - Created Permission View: can delete on DAG:twitter_dag
[2022-12-31T22:25:01.933+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.933+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:25:01.944+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.944+0700] {dag.py:2697} INFO - Creating ORM DAG for twitter_dag
[2022-12-31T22:25:01.955+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:01.955+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:25:02.000+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.629 seconds
[2022-12-31T22:25:53.170+0700] {processor.py:153} INFO - Started process (PID=49719) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:53.175+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:25:53.176+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:53.175+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:53.456+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:25:53.457+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:25:53.470+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:25:53.482+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:25:53.503+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:53.503+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:25:53.523+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:53.523+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:25:53.552+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.387 seconds
[2022-12-31T22:26:43.269+0700] {processor.py:153} INFO - Started process (PID=49859) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:26:43.272+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:26:43.274+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:43.274+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:26:43.599+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:26:43.600+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:26:43.616+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:26:43.629+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:26:43.650+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:43.650+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:26:43.669+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:43.669+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:26:43.698+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.437 seconds
[2022-12-31T22:27:31.823+0700] {processor.py:153} INFO - Started process (PID=50220) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:27:31.825+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:27:31.826+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:31.826+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:27:32.096+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:27:32.097+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:27:32.110+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:27:32.124+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:27:32.146+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:32.146+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:27:32.169+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:32.169+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:27:32.203+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.386 seconds
[2022-12-31T22:28:22.716+0700] {processor.py:153} INFO - Started process (PID=50587) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:28:22.720+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:28:22.721+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:22.721+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:28:22.993+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:28:22.994+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:28:23.010+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:28:23.022+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:28:23.042+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:23.042+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:28:23.062+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:23.062+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:28:23.094+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.382 seconds
[2022-12-31T22:29:10.444+0700] {processor.py:153} INFO - Started process (PID=50681) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:10.448+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:29:10.449+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:10.449+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:10.658+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:29:10.659+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:29:10.678+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:29:10.697+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:10.732+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:10.732+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:29:10.760+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:10.760+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:29:10.810+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.369 seconds
[2022-12-31T22:29:57.239+0700] {processor.py:153} INFO - Started process (PID=51283) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:57.244+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:29:57.244+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:57.244+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:57.400+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:29:57.401+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:29:57.414+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:29:57.428+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:29:57.452+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:57.452+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:29:57.473+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:57.473+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:29:57.498+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.262 seconds
[2022-12-31T22:30:45.682+0700] {processor.py:153} INFO - Started process (PID=51597) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:30:45.688+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:30:45.692+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:45.691+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:30:45.936+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:30:45.937+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:30:45.954+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:30:45.969+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:30:45.998+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:45.998+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:30:46.025+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:46.025+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:30:46.064+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.394 seconds
[2022-12-31T22:31:33.781+0700] {processor.py:153} INFO - Started process (PID=51787) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:31:33.782+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:31:33.783+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:33.783+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:31:34.035+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:31:34.036+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:31:34.062+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:31:34.093+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:31:34.134+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:34.133+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:31:34.169+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:34.169+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:31:34.214+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.438 seconds
[2022-12-31T22:32:22.498+0700] {processor.py:153} INFO - Started process (PID=51865) to work on /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:32:22.504+0700] {processor.py:743} INFO - Processing file /home/dmk/airflow/dags/twitter_dag.py for tasks to queue
[2022-12-31T22:32:22.506+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:22.506+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:32:22.753+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:33 DeprecationWarning: The `airflow.hooks.base_hook.BaseHook` class is deprecated. Please use `'airflow.hooks.base.BaseHook'`.
[2022-12-31T22:32:22.754+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/hooks/hive.py:34 DeprecationWarning: The `airflow.hooks.dbapi_hook.DbApiHook` class is deprecated. Please use `'airflow.providers.common.sql.hooks.sql.DbApiHook'`.
[2022-12-31T22:32:22.769+0700] {logging_mixin.py:137} WARNING - /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/apache/hive/operators/hive.py:30 RemovedInAirflow3Warning: This decorator is deprecated. 

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the `default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
[2022-12-31T22:32:22.787+0700] {processor.py:753} INFO - DAG(s) dict_keys(['twitter_dag']) retrieved from /home/dmk/airflow/dags/twitter_dag.py
[2022-12-31T22:32:22.816+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:22.816+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:32:22.839+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:22.839+0700] {dag.py:3427} INFO - Setting next_dagrun for twitter_dag to 2022-12-29T00:00:00+00:00, run_after=2022-12-30T00:00:00+00:00
[2022-12-31T22:32:22.902+0700] {processor.py:175} INFO - Processing /home/dmk/airflow/dags/twitter_dag.py took 0.414 seconds
