[2022-12-31T20:48:38.119+0700] {processor.py:153} INFO - Started process (PID=9403) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:48:38.120+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:48:38.121+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:48:38.121+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:48:38.137+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:48:38.136+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:48:38.137+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:48:38.137+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:48:38.137+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:48:38.144+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-12-31T20:54:55.693+0700] {processor.py:153} INFO - Started process (PID=11828) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:54:55.702+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:54:55.703+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:54:55.703+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:54:55.734+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:54:55.733+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:54:55.734+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:54:55.734+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:54:55.735+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:54:55.745+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2022-12-31T20:55:38.968+0700] {processor.py:153} INFO - Started process (PID=12040) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:55:38.972+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:55:38.972+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:55:38.972+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:55:38.992+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:55:38.991+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:55:38.992+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:55:38.992+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:55:38.992+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:55:39.001+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2022-12-31T20:56:22.139+0700] {processor.py:153} INFO - Started process (PID=12199) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:56:22.143+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:56:22.143+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:56:22.143+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:56:22.179+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:56:22.178+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:56:22.179+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:56:22.179+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:56:22.179+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:56:22.188+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-31T20:57:25.371+0700] {processor.py:153} INFO - Started process (PID=12496) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:57:25.375+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:57:25.375+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:57:25.375+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:57:25.398+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:57:25.397+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:57:25.398+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:57:25.398+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:57:25.398+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:57:25.406+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-31T20:58:18.653+0700] {processor.py:153} INFO - Started process (PID=12928) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:58:18.654+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:58:18.654+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:58:18.654+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:58:18.789+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:58:18.788+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:58:18.789+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:58:18.789+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:58:18.789+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:58:18.795+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.145 seconds
[2022-12-31T20:59:08.987+0700] {processor.py:153} INFO - Started process (PID=13105) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:08.993+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:59:08.996+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:08.996+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:09.053+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:09.052+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:59:09.054+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:09.054+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:59:09.054+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:09.064+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2022-12-31T20:59:55.203+0700] {processor.py:153} INFO - Started process (PID=14399) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:55.207+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T20:59:55.209+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:55.209+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:55.254+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:55.253+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T20:59:55.255+0700] {logging_mixin.py:137} INFO - [2022-12-31T20:59:55.255+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T20:59:55.256+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T20:59:55.271+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2022-12-31T21:00:53.844+0700] {processor.py:153} INFO - Started process (PID=15523) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:00:53.846+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:00:53.848+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:00:53.848+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:00:53.874+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:00:53.874+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:00:53.874+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:00:53.874+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:00:53.875+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:00:53.881+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-12-31T21:01:44.796+0700] {processor.py:153} INFO - Started process (PID=16232) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:01:44.800+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:01:44.800+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:01:44.800+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:01:44.816+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:01:44.816+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:01:44.817+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:01:44.816+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:01:44.817+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:01:44.823+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-12-31T21:02:38.320+0700] {processor.py:153} INFO - Started process (PID=16373) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:02:38.322+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:02:38.324+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:02:38.323+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:02:38.342+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:02:38.342+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:02:38.343+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:02:38.343+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:02:38.343+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:02:38.350+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2022-12-31T21:03:32.397+0700] {processor.py:153} INFO - Started process (PID=16850) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:03:32.399+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:03:32.400+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:03:32.400+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:03:32.415+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:03:32.415+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:03:32.416+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:03:32.415+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:03:32.416+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:03:32.422+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2022-12-31T21:04:25.425+0700] {processor.py:153} INFO - Started process (PID=17358) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:04:25.429+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:04:25.431+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:04:25.431+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:04:25.454+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:04:25.454+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:04:25.455+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:04:25.454+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:04:25.455+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:04:25.464+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-31T21:05:15.386+0700] {processor.py:153} INFO - Started process (PID=17866) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:05:15.392+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:05:15.394+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:05:15.393+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:05:15.423+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:05:15.423+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:05:15.423+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:05:15.423+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:05:15.424+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:05:15.431+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-31T21:06:15.887+0700] {processor.py:153} INFO - Started process (PID=18417) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:06:15.894+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:06:15.899+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:06:15.898+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:06:15.935+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:06:15.934+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:06:15.935+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:06:15.935+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:06:15.936+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:06:15.946+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2022-12-31T21:07:07.117+0700] {processor.py:153} INFO - Started process (PID=18637) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:07.121+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:07:07.122+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:07.122+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:07.136+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:07.136+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:07:07.136+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:07.136+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:07:07.136+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:07.144+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-12-31T21:07:51.476+0700] {processor.py:153} INFO - Started process (PID=18753) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:51.480+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:07:51.481+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:51.481+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:51.648+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:51.648+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:07:51.649+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:07:51.648+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:07:51.649+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:07:51.657+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.184 seconds
[2022-12-31T21:08:40.433+0700] {processor.py:153} INFO - Started process (PID=19077) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:08:40.438+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:08:40.439+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:08:40.439+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:08:40.465+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:08:40.464+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:08:40.465+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:08:40.465+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:08:40.465+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:08:40.473+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-31T21:09:30.950+0700] {processor.py:153} INFO - Started process (PID=19747) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:09:30.953+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:09:30.955+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:09:30.954+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:09:30.979+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:09:30.979+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:09:30.979+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:09:30.979+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:09:30.979+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:09:30.987+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-31T21:10:12.677+0700] {processor.py:153} INFO - Started process (PID=19887) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:10:12.682+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:10:12.684+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:10:12.684+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:10:12.715+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:10:12.715+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:10:12.716+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:10:12.715+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:10:12.716+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:10:12.726+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2022-12-31T21:11:02.182+0700] {processor.py:153} INFO - Started process (PID=20156) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:02.187+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:11:02.188+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:02.188+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:02.221+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:02.220+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:11:02.221+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:02.221+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:11:02.222+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:02.230+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2022-12-31T21:11:53.516+0700] {processor.py:153} INFO - Started process (PID=20340) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:53.518+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:11:53.519+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:53.519+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:53.541+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:53.540+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:11:53.541+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:11:53.541+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:11:53.542+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:11:53.552+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-12-31T21:12:50.713+0700] {processor.py:153} INFO - Started process (PID=20479) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:12:50.715+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:12:50.716+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:12:50.716+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:12:50.731+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:12:50.730+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:12:50.731+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:12:50.731+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:12:50.731+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:12:50.738+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-12-31T21:13:39.899+0700] {processor.py:153} INFO - Started process (PID=20691) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:13:39.903+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:13:39.903+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:13:39.903+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:13:39.918+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:13:39.918+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:13:39.919+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:13:39.919+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:13:39.919+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:13:39.926+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-12-31T21:14:16.124+0700] {processor.py:153} INFO - Started process (PID=21151) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:14:16.127+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:14:16.128+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:14:16.128+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:14:16.147+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:14:16.147+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:14:16.148+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:14:16.148+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:14:16.148+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:14:16.155+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2022-12-31T21:15:18.781+0700] {processor.py:153} INFO - Started process (PID=22084) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:15:18.785+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:15:18.785+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:15:18.785+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:15:18.800+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:15:18.800+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:15:18.801+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:15:18.800+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:15:18.801+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:15:18.807+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-12-31T21:16:03.104+0700] {processor.py:153} INFO - Started process (PID=22590) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:03.108+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:16:03.108+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:03.108+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:03.123+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:03.123+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:16:03.123+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:03.123+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:16:03.123+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:03.130+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-12-31T21:16:47.775+0700] {processor.py:153} INFO - Started process (PID=23243) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:47.779+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:16:47.780+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:47.780+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:47.797+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:47.797+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:16:47.798+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:16:47.797+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:16:47.798+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:16:47.805+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2022-12-31T21:17:36.312+0700] {processor.py:153} INFO - Started process (PID=23619) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:17:36.315+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:17:36.317+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:17:36.316+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:17:36.343+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:17:36.342+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:17:36.343+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:17:36.343+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:17:36.343+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:17:36.351+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-31T21:18:56.979+0700] {processor.py:153} INFO - Started process (PID=23975) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:18:56.983+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:18:56.984+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:56.984+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:18:57.010+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:57.009+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:18:57.011+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:18:57.010+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:18:57.011+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:18:57.023+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-31T21:19:47.979+0700] {processor.py:153} INFO - Started process (PID=24212) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:19:47.983+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:19:47.984+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:47.984+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:19:48.000+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:47.999+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:19:48.000+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:19:48.000+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:19:48.000+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:19:48.007+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-12-31T21:20:30.803+0700] {processor.py:153} INFO - Started process (PID=24447) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:20:30.809+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:20:30.811+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:30.810+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:20:30.867+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:30.866+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:20:30.868+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:20:30.868+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:20:30.868+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:20:30.879+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-12-31T21:22:21.235+0700] {processor.py:153} INFO - Started process (PID=25166) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:22:21.240+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:22:21.242+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:22:21.241+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:22:21.279+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:22:21.278+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:22:21.279+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:22:21.279+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:22:21.280+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:22:21.289+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2022-12-31T21:23:10.276+0700] {processor.py:153} INFO - Started process (PID=25377) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:10.278+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:23:10.279+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:10.278+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:10.296+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:10.296+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:23:10.296+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:10.296+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:23:10.296+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:10.303+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-12-31T21:23:52.973+0700] {processor.py:153} INFO - Started process (PID=25469) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:52.977+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:23:52.978+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:52.978+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:52.995+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:52.994+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:23:52.995+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:23:52.995+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:23:52.995+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:23:53.003+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2022-12-31T21:24:54.756+0700] {processor.py:153} INFO - Started process (PID=25708) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:24:54.760+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:24:54.761+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:54.761+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:24:54.789+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:54.789+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:24:54.790+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:24:54.790+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:24:54.790+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:24:54.798+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-31T21:25:48.304+0700] {processor.py:153} INFO - Started process (PID=25877) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:25:48.307+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:25:48.308+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:48.308+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:25:48.339+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:48.339+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:25:48.340+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:25:48.339+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:25:48.340+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:25:48.350+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-31T21:26:38.603+0700] {processor.py:153} INFO - Started process (PID=25976) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:26:38.608+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:26:38.610+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:38.609+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:26:38.760+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:38.759+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:26:38.760+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:26:38.760+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:26:38.760+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:26:38.768+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.177 seconds
[2022-12-31T21:27:41.171+0700] {processor.py:153} INFO - Started process (PID=26090) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:27:41.175+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:27:41.177+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:41.177+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:27:41.223+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:41.222+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:27:41.223+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:27:41.223+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:27:41.224+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:27:41.233+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2022-12-31T21:28:30.758+0700] {processor.py:153} INFO - Started process (PID=26171) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:28:30.762+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:28:30.765+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:30.764+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:28:30.816+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:30.815+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:28:30.816+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:28:30.816+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:28:30.817+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:28:30.826+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2022-12-31T21:29:10.765+0700] {processor.py:153} INFO - Started process (PID=26271) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:10.770+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:29:10.774+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:10.773+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:10.839+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:10.837+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:29:10.839+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:10.839+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:29:10.839+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:10.850+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2022-12-31T21:29:54.864+0700] {processor.py:153} INFO - Started process (PID=26382) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:54.869+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:29:54.873+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:54.872+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:54.938+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:54.937+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:29:54.939+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:29:54.939+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:29:54.939+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:29:54.952+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2022-12-31T21:30:36.410+0700] {processor.py:153} INFO - Started process (PID=26473) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:30:36.414+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:30:36.415+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:36.415+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:30:36.444+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:36.443+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:30:36.444+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:30:36.444+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:30:36.445+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:30:36.458+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-31T21:31:32.128+0700] {processor.py:153} INFO - Started process (PID=26572) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:31:32.132+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:31:32.133+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:32.133+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:31:32.158+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:32.157+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:31:32.158+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:31:32.158+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:31:32.158+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:31:32.166+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-31T21:32:15.866+0700] {processor.py:153} INFO - Started process (PID=26651) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:15.871+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:32:15.874+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:15.873+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:15.919+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:15.918+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:32:15.919+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:15.919+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:32:15.919+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:15.933+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2022-12-31T21:32:59.766+0700] {processor.py:153} INFO - Started process (PID=26734) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:59.773+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:32:59.775+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:59.775+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:59.832+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:59.831+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:32:59.832+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:32:59.832+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:32:59.832+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:32:59.845+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2022-12-31T21:34:00.317+0700] {processor.py:153} INFO - Started process (PID=26907) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:00.321+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:34:00.321+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:00.321+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:00.341+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:00.341+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:34:00.342+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:00.342+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:34:00.342+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:00.352+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2022-12-31T21:34:29.769+0700] {processor.py:153} INFO - Started process (PID=27501) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:29.770+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:34:29.771+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:29.771+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:29.793+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:29.792+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:34:29.793+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:34:29.793+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:34:29.794+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:34:29.803+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-12-31T21:35:18.098+0700] {processor.py:153} INFO - Started process (PID=27852) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:35:18.103+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:35:18.105+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:18.105+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:35:18.133+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:18.133+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:35:18.134+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:35:18.134+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:35:18.134+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:35:18.141+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-31T21:38:01.480+0700] {processor.py:153} INFO - Started process (PID=28791) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:01.483+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:38:01.484+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:01.484+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:01.522+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:01.521+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:38:01.522+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:01.522+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:38:01.523+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:01.533+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-31T21:38:53.592+0700] {processor.py:153} INFO - Started process (PID=29017) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:53.596+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:38:53.598+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:53.598+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:53.632+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:53.631+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:38:53.632+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:38:53.632+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:38:53.632+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:38:53.641+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2022-12-31T21:39:40.826+0700] {processor.py:153} INFO - Started process (PID=29193) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:39:40.828+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:39:40.831+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:40.831+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:39:40.852+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:40.852+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:39:40.853+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:39:40.853+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:39:40.853+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:39:40.860+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-12-31T21:40:29.239+0700] {processor.py:153} INFO - Started process (PID=29440) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:40:29.243+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:40:29.243+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:29.243+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:40:29.258+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:29.257+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:40:29.258+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:40:29.258+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:40:29.258+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:40:29.265+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-12-31T21:41:13.844+0700] {processor.py:153} INFO - Started process (PID=29521) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:41:13.848+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:41:13.849+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:13.849+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:41:13.864+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:13.863+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:41:13.864+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:41:13.864+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:41:13.864+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:41:13.872+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-12-31T21:42:00.847+0700] {processor.py:153} INFO - Started process (PID=29726) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:00.852+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:42:00.853+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:00.853+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:00.872+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:00.871+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:42:00.872+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:00.872+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:42:00.872+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:00.879+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-31T21:42:49.778+0700] {processor.py:153} INFO - Started process (PID=29882) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:49.785+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T21:42:49.785+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:49.785+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:49.803+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:49.802+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T21:42:49.803+0700] {logging_mixin.py:137} INFO - [2022-12-31T21:42:49.803+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T21:42:49.803+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T21:42:49.811+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2022-12-31T22:20:45.777+0700] {processor.py:153} INFO - Started process (PID=46111) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:20:45.786+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:20:45.787+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:20:45.787+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:20:45.811+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:20:45.810+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T22:20:45.811+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:20:45.811+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T22:20:45.812+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:20:45.831+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2022-12-31T22:22:59.888+0700] {processor.py:153} INFO - Started process (PID=47535) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:22:59.891+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:22:59.892+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:59.892+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:22:59.912+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:59.911+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T22:22:59.913+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:22:59.913+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T22:22:59.913+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:22:59.922+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-12-31T22:23:47.533+0700] {processor.py:153} INFO - Started process (PID=47869) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:23:47.538+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:23:47.542+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:47.541+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:23:47.599+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:47.598+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T22:23:47.600+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:23:47.600+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T22:23:47.600+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:23:47.615+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2022-12-31T22:24:31.249+0700] {processor.py:153} INFO - Started process (PID=48292) to work on /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:24:31.253+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:24:31.255+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:31.254+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:24:31.309+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:31.308+0700] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-31T22:24:31.310+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:24:31.310+0700] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-31T22:24:31.310+0700] {processor.py:755} WARNING - No viable dags retrieved from /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:24:31.324+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2022-12-31T22:25:07.669+0700] {processor.py:153} INFO - Started process (PID=48762) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:07.676+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:25:07.680+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:07.679+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:07.726+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:07.984+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:07.984+0700] {manager.py:504} INFO - Created Permission View: can read on DAG:example_local_kubernetes_executor
[2022-12-31T22:25:08.013+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:08.012+0700] {manager.py:504} INFO - Created Permission View: can edit on DAG:example_local_kubernetes_executor
[2022-12-31T22:25:08.051+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:08.050+0700] {manager.py:504} INFO - Created Permission View: can delete on DAG:example_local_kubernetes_executor
[2022-12-31T22:25:08.052+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:08.051+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:25:08.075+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:08.075+0700] {dag.py:2697} INFO - Creating ORM DAG for example_local_kubernetes_executor
[2022-12-31T22:25:08.087+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:08.087+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:25:08.117+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.461 seconds
[2022-12-31T22:25:59.571+0700] {processor.py:153} INFO - Started process (PID=49752) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:59.576+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:25:59.578+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:59.577+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:59.609+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:25:59.738+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:59.738+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:25:59.757+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:25:59.757+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:25:59.790+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.224 seconds
[2022-12-31T22:26:48.858+0700] {processor.py:153} INFO - Started process (PID=49938) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:26:48.863+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:26:48.865+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:48.864+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:26:48.893+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:26:49.023+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:49.022+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:26:49.042+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:26:49.041+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:26:49.072+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.221 seconds
[2022-12-31T22:27:37.329+0700] {processor.py:153} INFO - Started process (PID=50231) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:27:37.334+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:27:37.335+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:37.335+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:27:37.474+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:27:37.494+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:37.494+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:27:37.513+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:27:37.513+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:27:37.543+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.223 seconds
[2022-12-31T22:28:28.026+0700] {processor.py:153} INFO - Started process (PID=50598) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:28:28.030+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:28:28.032+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:28.031+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:28:28.172+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:28:28.191+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:28.191+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:28:28.211+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:28:28.211+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:28:28.245+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.225 seconds
[2022-12-31T22:29:16.393+0700] {processor.py:153} INFO - Started process (PID=50700) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:29:16.399+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:29:16.403+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:16.402+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:29:16.472+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:29:16.507+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:16.507+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:29:16.532+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:29:16.532+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:29:16.563+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.180 seconds
[2022-12-31T22:30:02.822+0700] {processor.py:153} INFO - Started process (PID=51293) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:02.826+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:30:02.828+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:02.827+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:02.857+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:02.880+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:02.880+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:30:02.901+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:02.901+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:30:02.937+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2022-12-31T22:30:51.430+0700] {processor.py:153} INFO - Started process (PID=51606) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:51.433+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:30:51.435+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:51.435+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:51.463+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:30:51.487+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:51.487+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:30:51.507+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:30:51.507+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:30:51.544+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.125 seconds
[2022-12-31T22:31:38.724+0700] {processor.py:153} INFO - Started process (PID=51799) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:31:38.728+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:31:38.730+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:38.729+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:31:38.766+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:31:38.792+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:38.792+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:31:38.818+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:31:38.818+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:31:38.853+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2022-12-31T22:32:27.920+0700] {processor.py:153} INFO - Started process (PID=51875) to work on /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:32:27.923+0700] {processor.py:743} INFO - Processing file /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-31T22:32:27.924+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:27.924+0700] {dagbag.py:538} INFO - Filling up the DagBag from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:32:27.970+0700] {processor.py:753} INFO - DAG(s) dict_keys(['example_local_kubernetes_executor']) retrieved from /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-31T22:32:28.010+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:28.009+0700] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-31T22:32:28.036+0700] {logging_mixin.py:137} INFO - [2022-12-31T22:32:28.036+0700] {dag.py:3427} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2022-12-31T22:32:28.070+0700] {processor.py:175} INFO - Processing /home/dmk/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.161 seconds
